_select_data:
  aspect-ratios:
    one-third: 
    one-half: 
    two-thirds: 
    full-width: 

  column-sizes:
    col-one-third: one-third
    col-one-half: one-half
    col-two-thirds: two-thirds
    col-full-width: full-width